name: ML CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Cache pip packages
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # 5. Lint (optional but recommended)
      - name: Run flake8
        run: |
          pip install flake8
          flake8 .

      # 6. Run Unit Tests
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

      # 7. Small-Scale Training
      - name: Train model
        run: python train.py

      # 8. Evaluate & Enforce Threshold
      - name: Check performance
        run: python check_performance.py
