# 

# .github/workflows/ci.yml
name: ML CI + CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 . --exclude .venv

      - name: Run Unit Tests (pytest)
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Train model
        run: python train.py

      - name: Check performance
        run: python check_performance.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: artifacts/model.pkl

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model-artifact
          path: artifacts/

      - name: Deploy to Staging (stub)
        run: |
          echo "✅ All CI checks passed!"
          echo "📦 Would now deploy artifacts/model.pkl to your staging environment."
          echo "    (e.g. scp, docker push, kubectl set image, etc.)"
